version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    versioning-strategy: increase
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: '@types/vscode'
      - dependency-name: vscode-languageclient
      - dependency-name: '@vscode/test-electron'
      - dependency-name: chai
        versions: ['>=5']
      - dependency-name: '@types/chai'
        versions: ['>=5']
    groups:
      minor-and-patch:
        patterns: ['*']
        update-types: [minor, patch]
      major:
        patterns: ['*']
        update-types: [major]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    groups:
      minor-and-patch:
        patterns: ['*']
        update-types: [minor, patch]
      major:
        patterns: ['*']
        update-types: [major]
