name: Test Jbeam Edit extension

on:
  push:
    branches: [main]
  pull_request:

jobs:
  integration-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - run: npm clean-install
      - name: Check formatting with js-beautify
        run: |
          npm run format
          git diff --exit-code
      - name: Install and start jbeam-lsp-server
        run: powershell -ExecutionPolicy Bypass -File ./scripts/setup-server.ps1
      - run: npm run build
      - name: Run integration tests
        run: npx mocha -r ts-node/register tests/integration/**/*.ts --timeout 60000
