name: Test Jbeam Edit extension

on:
  push:
    branches: [main]
  pull_request:

jobs:
  integration-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - run: npm clean-install
      - name: Check formatting with js-beautify
        run: |
          npm run format
          git diff --exit-code
      - name: Setup jbeam language server
        run: |
          mkdir C:\jbeam-lsp-server
          cd C:\jbeam-lsp-server
          gh release download 0.0.4 --repo webdevred/jbeam_edit --pattern "setup.exe"
          ./jbeam-edit-setup.exe /S
      - name: Start jbeam-lsp-server
        run: Start-Process "jbeam-lsp-server"
      - run: npm run build
      - run: npm run test:integration
